name: rss_news
description: News of the world

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router: ^10.2.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  sqflite: ^2.3.0
  url_launcher: ^6.1.14
  xml: ^6.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
